### ISSUE TITLE
EventStream won't close on servers like Vercel

### ISSUE THREAD

**Issue by incarnateTheGreat** [moishinetzer/remix-live-loader#6]
Hey there.

Thanks for this live loader solution; it has really helped me!

I have run into an issue though: I'm using this method to stream live event data. Once the event is finished, I don't want to stream anymore. I tried using `AbortController` to kill the process in the `createEventStream` function, but for some reason it keeps re-firing the stream call. 

Have you experienced any issues with EventStream on servers like Vercel? I've heard some things, but otherwise nothing concrete. I tried following [this explanation](https://sergiodxa.com/tutorials/close-sse-connection-from-the-server-in-remix), but it didn't stop the event stream calls.

Thanks in advance!

Edit: [this might be the problem](https://vercel.com/docs/limits/overview#websockets)

**Comment by moishinetzer** [comment]
Hi, thanks for reaching out. 

This does not appear to be an issue with this package, and unfortunately I do not use Vercel for my deploys. If you can create a repro and link it here, I'll be glad to investigate further, however for now I'm going to close this issue as it does not appear to be an issue with this package specifically.

**Comment by incarnateTheGreat** [comment]
> Hi, thanks for reaching out.
> 
> This does not appear to be an issue with this package, and unfortunately I do not use Vercel for my deploys. If you can create a repro and link it here, I'll be glad to investigate further, however for now I'm going to close this issue as it does not appear to be an issue with this package specifically.

I've tried simplifying the code by basically opening up an event stream with no other logic. Something tells me Vercel just doesn't handle event streams well.

May I ask where you deploy to? I'd like to try another environment so I can perhaps test and possibly confirm that this is indeed an environment issue; it works perfectly fine on my local build. 

Cheers.

**Comment by moishinetzer** [comment]
I'm a big fan of fly.io give it a shot there.
